#!/bin/sh

# compile and upload the program.
make
make upload

# start openocd and fork it to the background.
"$HOME/.comp2300/openocd/bin/openocd" -f interface/stlink.cfg -f target/stm32l4x.cfg -c "program program.elf verify reset" &

# wait for openocd to actually connect before trying to talk to it.. :P
sleep 1s

# start the gdb instance.
"$HOME/.comp2300/arm-none-eabi/bin/arm-none-eabi-gdb" ./program.elf -ex 'target extended-remote :3333' -ex 'monitor reset halt' -ex 'b main' -ex 'c'

# when gdb exits, kill openocd.
pkill openocd
