#!/bin/sh

BG_LINK="${XDG_DATA_HOME:-$HOME/.local/share/}/bg"
BG="$(readlink -f "$BG_LINK")"
DIR="$(dirname "$BG")"
NEW_BG="$(next-file "$BG")"

xwallpaper --zoom "$DIR/$NEW_BG"
ln -sf "$DIR/$NEW_BG" "$BG_LINK"

echo "old background: $(basename "$BG")"
echo "new background: $NEW_BG"
