#!/bin/bash
# change picom settings at runtime using dmenu


COLOR='#b4eded'


# -- Choose a setting -- #

# get mode
MODE="$(echo -e "toggle\nchange settings" \
    | dmenu -sb "$COLOR" -p "what would you like to do?")"

[ "$MODE" = "toggle" ] && ( killall picom || picom -b ) && exit
[ "$MODE" = "change settings" ] || exit

# if changing settings, get a setting to change
SETTING="$(echo -e "opacity\ncorners\nfade\ndim" \
    | dmenu -sb "$COLOR" -p "change which setting?")"


# -- Set the setting -- #

# opacity
[ "$SETTING" = "opacity" ] && OPACITY=$(\

    echo -e "matte\nslightly transparent\ntransparent\nvery transparent\nextremely transparent\ninactive transparent\ncustom" \
    | dmenu -sb "$COLOR" -p "change opacity to what?")

[ "$OPACITY" = "matte" ] && \
    picom-config --active-opacity 1 --inactive-opacity 1 && exit
[ "$OPACITY" = "slightly transparent" ] && \
    picom-config --active-opacity 0.95 --inactive-opacity 0.8 && exit
[ "$OPACITY" = "transparent" ] && \
    picom-config --active-opacity 0.9 --inactive-opacity 0.7 && exit
[ "$OPACITY" = "very transparent" ] && \
    picom-config --active-opacity 0.7 --inactive-opacity 0.5 && exit
[ "$OPACITY" = "extremely transparent" ] && \
    picom-config --active-opacity 0.5 --inactive-opacity 0.3 && exit
[ "$OPACITY" = "inactive transparent" ] && \
    picom-config --active-opacity 1 --inactive-opacity 0.5 && exit

[ "$OPACITY" = "custom" ] && \
    A_OPACITY=$(dmenu -sb "$COLOR" -p "active opacity:") && \
    I_OPACITY=$(dmenu -sb "$COLOR" -p "inactive opacity:") && \
    picom-config --active-opacity "$A_OPACITY" --inactive-opacity "$I_OPACITY" \
    && exit

# corners
[ "$SETTING" = "corners" ] && RADIUS=$(echo -e "0\n5\n10\n15\n20" \
    | dmenu -sb "$COLOR" -p "corner radius:") && \
    picom-config --corner-radius "$RADIUS" && exit

# fade
[ "$SETTING" = "fade" ] && FADE=$(echo -e "0.03\n0.06" \
    | dmenu -sb "$COLOR" -p "change corners to what?") && \
    picom-config --fade-step "$FADE" && exit

# dim
[ "$SETTING" = "dim" ] && DIM=$(echo -e "0\n0.1\n0.2\n0.3\n0.4\n0.5\n0.6" \
    | dmenu -sb "$COLOR" -p "inactive dim:") && \
    picom-config --inactive-dim "$DIM" && exit
