#!/bin/sh

# opout: "open output": A general handler for opening a file's intended output,
# usually the pdf of a compiled document.

basename="$(echo "${*}" | sed 's/\.[^\/.]*$//')"

case "${*}" in
	*.rs) cargo test -- --include-ignored ;;
	*.hs) stack test ;;
esac
