#!/bin/sh

# ╠══════╬══════╬══════╬══════╬══════╣
# ║      ║      ║      ║      ║ e381 ║
# ║      ║      ║      ║      ║     ║
# ╠══════╬══════╬══════╬══════╬══════╣
# ║ e382 ║ e383 ║ e384 ║ e385 ║ e386 ║
# ║     ║     ║     ║     ║     ║
# ╠══════╬══════╬══════╬══════╬══════╣
# ║ e387 ║ e388 ║ e389 ║ e38a ║ e38b ║
# ║     ║     ║     ║     ║     ║
# ╠══════╬══════╬══════╬══════╬══════╣
# ║ e38c ║      ║      ║      ║      ║
# ║     ║      ║      ║      ║      ║
# ╠══════╬══════╬══════╬══════╬══════╣

clock=$(date '+%I')

case "$clock" in
	"00") icon="" ;;
	"01") icon="" ;;
	"02") icon="" ;;
	"03") icon="" ;;
	"04") icon="" ;;
	"05") icon="" ;;
	"06") icon="" ;;
	"07") icon="" ;;
	"08") icon="" ;;
	"09") icon="" ;;
	"10") icon="" ;;
	"11") icon="" ;;
	"12") icon="" ;;
esac

case $BLOCK_BUTTON in
	1) notify-send -u low "This Month" "$(cal --color=always \
        | sed "s/..7m/<b><span color=\"#b63740\">/;s/..27m/<\/span><\/b>/")" \
        && notify-send "Appointments" "$(calcurse -d7)" ;;
	2) setsid -f "$TERMINAL" -e calcurse ;;
    3) notify-send "📅 Time/date module" "\- Left click to show upcoming appointments for the next seven days.\n- Middle click to open calcurse if installed\n\- Right click to show this message" ;;
    6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

date "+%d/%m/%Y %I:%M%p"
