#!/bin/sh

# shell
alias c="clear"
alias ccat="highlight --out-format=ansi"
alias clear="message"
alias cp="cp -v"
alias grep="grep --color=auto"
alias la="ls -a"
alias ll="ls -l"
alias ln="ln -v"
alias ls="ls -hN --color=auto --group-directories-first"
alias mkd="mkdir"
alias mkdir="mkdir -pv"
alias mv="mv -v"
alias rm="rm -v"
alias stow="stow -v"
alias sx="startx >/dev/null 2>&1"

# general
alias SS="sudo systemctl"
alias YT="youtube-viewer"
alias e="$EDITOR"
alias f="vifm"
alias m="neomutt"
alias mutt="neomutt"
alias n="newsboat"
alias s="ddgr"
alias sf="sudo vifm"
alias sv="sudo $EDITOR"
alias t="setsid $TERMINAL >/dev/null 2>&1 & ; sleep 0.5 ; clear"
alias vifm="vifmrun"
alias vimwiki="$EDITOR -c VimwikiIndex"
alias yt="youtube-dl -ic"
alias yta="youtube-dl -xic"

alias anaconda="source /opt/anaconda/bin/activate root"
alias smk="sudo cp config.def.h config.h && sudo make clean install"

# config
alias i3c="$EDITOR ~/.config/i3/config"
alias vifmrc="$EDITOR ~/.config/vifm/vifmrc"
alias vrc="$EDITOR ~/.config/nvim/init.vim"
alias xrc="$EDITOR ~/.xinitrc"
alias zrc="$EDITOR $ZDOTDIR/.zshrc"

# fixes
alias abook="abook --config "$XDG_CONFIG_HOME"/abook/abookrc --datafile "$XDG_DATA_HOME"/abook/addressbook"
alias gbd="gdb -nh -x "$XDG_CONFIG_HOME"/gdb/init"
alias mvn="mvn -gs "$XDG_CONFIG_HOME"/maven/settings.xml"

# git
alias ga="git add"
alias gb="git checkout"
alias gc="git commit -m"
alias gf="git fetch"
alias gm="git merge"
alias gp="git push"
alias gr="git restore --staged"
alias gs="git status"
alias gv="git status -v"

alias gl="git log -30 --graph \
    --pretty=format:'¶%h %s' \
    | column -t -s '¶' -W3"
alias gll="git log --graph"

# alias gll="git log -30 --graph \
#     --pretty=format:'¶%h¶%ad¶%an¶%s' \
#     --date=format:'%Y-%m-%d %H:%M' \
#     | column -t -s '¶' -W5 -T4"

# pacman
type -p pacman >/dev/null 2>&1 && {
    alias R="sudo pacman -Rns"
    alias Rorphs="pacman -Qtdq | sudo pacman -Rns -"
    alias S="sudo pacman -S"
    alias p="sudo pacman"
    alias syu="sudo pacman -Syu"
}
