#!/bin/sh

# shell
alias c="clear"
alias ccat="highlight --out-format=ansi"
alias clear="message"
alias cp="cp -v"
alias grep="grep --color=auto"
alias la="ls -a"
alias ll="ls -l"
alias ln="ln -v"
alias ls="ls -hN --color=auto --group-directories-first"
alias mkd="mkdir"
alias mkdir="mkdir -pv"
alias mv="mv -v"
alias rm="rm -v"
alias stow="stow -v"
alias sx="startx"

# general
alias SS="sudo systemctl"
alias YT="youtube-viewer"
alias e="$EDITOR"
alias f="vifm"
alias m="neomutt"
alias mutt="neomutt"
alias n="newsboat"
alias sf="sudo vifm"
alias sv="sudo $EDITOR"
alias t="setsid $TERMINAL >/dev/null & ; sleep 0.5 ; clear"
alias vifm="vifmrun"
alias vimwiki="$EDITOR -c VimwikiIndex"
alias yt="youtube-dl -ic"
alias yta="youtube-dl -xic"

alias anaconda="source /opt/anaconda/bin/activate root"
alias smk="sudo cp config.def.h config.h && sudo make clean install"

# config
alias i3c="nvim ~/.config/i3/config"
alias vifmrc="nvim ~/.config/vifm/vifmrc"
alias vrc="nvim ~/.config/nvim/init.vim"
alias xrc="nvim ~/.xinitrc"
alias zrc="nvim $ZDOTDIR/.zshrc"

# fixes
alias abook="abook --config "$XDG_CONFIG_HOME"/abook/abookrc --datafile "$XDG_DATA_HOME"/abook/addressbook"
alias gbd="gdb -nh -x "$XDG_CONFIG_HOME"/gdb/init"
alias mvn="mvn -gs "$XDG_CONFIG_HOME"/maven/settings.xml"

# git
alias ga="git add"
alias gc="git commit -m"
alias gf="git fetch"
alias gm="git merge"
alias gp="git push"
alias gr="git restore --staged"
alias gs="git status"
alias gv="git status -v"

# pacman
alias R="sudo pacman -Rns"
alias Rorphs="pacman -Qtdq | sudo pacman -Rns -"
alias S="sudo pacman -S"
alias p="sudo pacman"
alias syu="sudo pacman -Syu"
